### ISSUE TITLE
Dropzone smart contract

### ISSUE THREAD

**Issue by bookmoons** [MyBitFoundation/dapp-dropzone#5]
I wonder if the team would consider doing the Dropzone smart contract through the DDF. Since the frontend is being built in https://github.com/MyBitFoundation/MyBit-Network.tech/issues/147, maybe we could have the app live for the token sale.

[`bookmoons/dropzone`](https://github.com/bookmoons/MyBit-Dropzone.tech/tree/bookmoons/dropzone) has something toward it, based on material on the website and the existing code. Coverage is 100%. [Diff](https://github.com/bookmoons/MyBit-Dropzone.tech/compare/0fbbd45c221a518ecc4404b71a7f193cc0df5c8d...6a92b5d5c9e01bd00b268ae5177fcf07056a57a6). 

```
-----------------------|----------|----------|----------|----------|----------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------|----------|----------|----------|----------|----------------|
..
  Dropzone.sol         |      100 |      100 |      100 |      100 |                |
```

```solidity
/**
 * @title Token airdropping
 * @notice
 * Anyone can send an airdrop of any ERC20 token.
 *
 * Provide the address of the token contract, recipients, and amounts to
 * airdrop. Use `airdropIdentical` to airdrop an identical amount to each
 * recipient. Use `airdropVariable` to specify a separate amount for each
 * recipient.
 */
contract Dropzone {
..
```

---

The feature set seems to be like this:
* Airdrop an identical amount to each of a list of recipients.
* Airdrop variable amounts to a list of recipients.
* Burn 250 MYB on each airdrop.

Deriving from the current code, the interface is like this:

| Method | Description |
| --- | --- |
| `airdropIdentical` | Airdrop an identical token amount to each recipient. |
| `airdropVariable` | Airdrop to list of recipients with a separate amount specified for each. |

There's 1 event emitted:

| Event | Description |
| --- | --- |
| `Airdrop` | An airdrop was performed. |

**Comment by pacamara** [comment]
@bookmoons Hi! What's the advantage of your refactored contracts over the current ones? The existing ones have methods `sendAirdrop` (for differing amounts) and `sendAirdropEqual`, emitting event `LogTokensTransferred`. They work fine for me so far. [Example airdrop txn on ropsten](https://ropsten.etherscan.io/tx/0xb59e324b7aeb923424ba264f3b1d49696fb3566a84faff6ad5aeb2d9d15ee947) What problems with them does your refactor fix?

**Comment by bookmoons** [comment]
It moves them toward something with complete tests. I think the current code was intended as something temporary to build around, with something clean and complete to be built later. As the issue says they're not yet finalised:
>The smart contracts are not finalised and solely serve to act as the building blocks for this use case.

It aims for something that can be comfortably deployed on the livenet. There may be changes needed, but it's intended as a first step. Everything is well commented, and it uses the condition oriented programming pattern [recommended by Gavin](https://medium.com/@gavofyork/condition-orientated-programming-969f6ba0161a). The name changes are cosmetic, following the same structure and just simplifying a little.
